apiVersion: v1
kind: Namespace
metadata:
  name: advisorconnect-prod
  labels:
    app.kubernetes.io/part-of: advisorconnect
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: advisorconnect-infra
  labels:
    app.kubernetes.io/part-of: advisorconnect
    environment: infrastructure
---
apiVersion: v1
kind: Namespace
metadata:
  name: advisorconnect-monitoring
  labels:
    app.kubernetes.io/part-of: advisorconnect
    environment: monitoring
